name: 'training spawner with single fixed hp set'

resources:
  conda_env: 'pytorch'
  wandb_project: 'flareon'
  cluster: 'baobab'

logging:
  record: false

parameters:
  # Generic
  task: 'train'
  algo: 'bcq'
  cuda: false
  num_seeds: 3
  benchmark: 'd4rl'

  # Training
  save_frequency: 1e5
  num_steps: 5e5
  training_steps_per_iter: 1
  eval_steps_per_iter: 10
  eval_frequency: 10

  # Model
  perception_stack: '"400 300, 400 300, 750 750"'
  layer_norm: true

  # Optimization
  actor_lr: 1.0e-4
  critic_lr: 1.0e-3
  lr_schedule: 'linear'
  clip_norm: 0.
  wd_scale: 0.

  # Algorithm
  batch_size: 100
  gamma: 0.99
  mem_size: 1e6
  polyak: 0.005
  targ_up_freq: 100
  n_step_returns: false
  lookahead: 10
  ret_norm: false
  popart: false

  # TD3
  clipped_double: true
  ensemble_q_lambda: 0.75
  targ_actor_smoothing: false
  td3_std: 0.2
  td3_c: 0.5
  actor_update_delay: 1

  # Prioritized replay
  prioritized_replay: false
  alpha: 0.3
  beta: 1.
  ranked: false
  unreal: false

  # Distributional RL
  use_c51: false
  use_qr: false
  c51_num_atoms: 151
  c51_vmin: -150.
  c51_vmax: 150.
  num_tau: 200

  # Offline RL
  offline: true
  use_expert_demos: false
  sub_rate: 20

  bcq_phi: 0.05
  behavior_lr: 3.0e-4
