meta:
  task: 'train'
  benchmark: 'd4rl'
  algo: 'ddpg'

resources:
  cuda: true
  gpu_index: 0

logging:
  wandb_project: 'flareon'
  record: false

# Training
save_frequency: 1e5
num_steps: 5e5
training_steps_per_iter: 1
eval_steps_per_iter: 50
eval_frequency: 5e3

# Model
perception_stack: '"400 300, 400 300"'
layer_norm: true

# Optimization
actor_lr: 1.0e-4
critic_lr: 3.0e-4
lr_schedule: 'constant'
clip_norm: 0.
wd_scale: 0.

# Algorithm
rollout_len: 2
batch_size: 64
gamma: 0.99
mem_size: 2e6
noise_type: '"adaptive-param_0.2, ou_0.2"'
pn_adapt_frequency: 50
polyak: 0.005
targ_up_freq: 100
n_step_returns: true
lookahead: 10
obs_norm: false
ret_norm: false
popart: false

# TD3
clipped_double: false
ensemble_q_lambda: 1.
targ_actor_smoothing: false
td3_std: 0.2
td3_c: 0.5
actor_update_delay: 2

# Prioritized replay
prioritized_replay: false
alpha: 0.3
beta: 1.
ranked: false
unreal: false

# Distributional RL
use_c51: false
use_qr: true
c51_num_atoms: 51
c51_vmin: -150.
c51_vmax: 150.
num_tau: 200

# Offline RL
offline: true
